# Generated by Django 3.2.10 on 2022-10-20 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekichabi.district')),
            ],
        ),
        migrations.CreateModel(
            name='Subvillage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekichabi.village')),
            ],
            options={
                'ordering': ['village__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subsector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekichabi.category')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('ward', models.CharField(max_length=15)),
                ('number1', models.CharField(max_length=15)),
                ('number2', models.CharField(max_length=15)),
                ('crop1', models.CharField(max_length=50)),
                ('crop2', models.CharField(max_length=50)),
                ('crop3', models.CharField(max_length=50)),
                ('livestock1', models.CharField(max_length=50)),
                ('livestock2', models.CharField(max_length=50)),
                ('livestock3', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekichabi.category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekichabi.district')),
                ('subsector1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsector1', to='ekichabi.subsector')),
                ('subsector2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsector2', to='ekichabi.subsector')),
                ('subvillage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekichabi.subvillage')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekichabi.village')),
            ],
        ),
    ]
