# Generated by Django 3.2.10 on 2022-10-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekichabi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, default='', max_length=25)),
                ('phone_num', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
