# Generated by Django 3.2.10 on 2022-11-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekichabi', '0003_remove_whitelist_device_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['name'], name='ekichabi_bu_name_599513_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner'], name='ekichabi_bu_owner_391ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['category'], name='ekichabi_bu_categor_fd1053_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['district'], name='ekichabi_bu_distric_a92a49_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['village'], name='ekichabi_bu_village_cd4415_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['subvillage'], name='ekichabi_bu_subvill_b692e0_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['subsector1'], name='ekichabi_bu_subsect_f9991f_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['subsector2'], name='ekichabi_bu_subsect_8fea98_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['crop1'], name='ekichabi_bu_crop1_e9f5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['crop2'], name='ekichabi_bu_crop2_651baf_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['crop3'], name='ekichabi_bu_crop3_f3ab9a_idx'),
        ),
    ]
